### ISSUE TITLE
Configuration problem.

### ISSUE THREAD

**Issue by Achaean** [tinyclub/vnstatsvg#1]
hi! :-)

./configure gives me the error: "checking command: apache2... there is no command apache2 installed in your system, if you want to continue, please install it firstly."

I'm on Debian Jessie x64 KDE.
(Apache2 is already installed).
A.

**Comment by lzufalcon** [comment]
Perhaps you can manually change the apache2 check command, the ./configure script may not cover all of the distributions. try to change 'apache2' to the name of apache2 in Debian?

function check_command:

```
echo -n "checking command: $1... "  
which $1
ret=$?
if [ $ret -ne 0 ]; then
    case $1 in
    apache2)
        which httpd
        ret=$?
        if [ $ret -ne 0 ]; then
            which httpd2
            ret=$?
                            if [ $ret -ne 0 ]; then
                                    which nginx
                                    ret=$?
                            fi
        fi
        ;;
```

**Comment by Achaean** [comment]
THANKS  lzufalcon! :-)

I'm starting Apache, giving (as root): "systemctl start apache2".
What do I have to write at configure (instead of apache2)?
I tried adding "systemctl start", before "apache2", but that didn't work.
Thanks again! :-)
A.

**Comment by lzufalcon** [comment]
Hi, @Achaean 

Please revert the change of ./configure and run "git pull", then, replace the following apache2 with the one in your debian or simply remove the following apache2:

150                 for i in vnstat cron gawk apache2 sort grep
151                 do
152                         check_command $i
153                 done
154         ;;

Or else, please comment the above lines if you make sure the above tools have been installed.

**Comment by Achaean** [comment]
Thanks!
I'll do it. :-)
