### ISSUE TITLE
how to configure on a https site

### ISSUE THREAD

**Issue by cayxxx** [tinyclub/vnstatsvg#2]
It has worked very well on my http site . But since i turned my site to https , it can't show any traffic information excepet "loading" whatever I select summary, month, day or hour.
How can I fix this ?Please help!

**Comment by cayxxx** [comment]
I have figured it out . Using https , the hostname in sidebar.xml must be the domain name instead of 'localhost'.

**Comment by lzufalcon** [comment]
@cayxxx congratulation!
